Add simulate rule in Snakefile

diff --git a/benchmarks/u_rho/Snakefile b/benchmarks/u_rho/Snakefile
--- a/benchmarks/u_rho/Snakefile
+++ b/benchmarks/u_rho/Snakefile
@@ -36,10 +36,36 @@ rule uchannelrho_campaign_raw_get:
 echo "Getting afterburned event-generator file"
 ln {input} {output}
 ls benchmark_output/
-mkdir -p input/u_rho
-cp {output} input/u_rho/
-echo "File in input/u_rho/:"
-ls input/u_rho/
+"""
+
+rule uchannelrho_simulate:
+    input:
+        "benchmark_output/rho_10x100_uChannel_Q2of0to10_hiDiv.hepmc3.tree.root",
+    output:
+        "benchmark_output/rho_10x100_uChannel_Q2of0to10_hiDiv.hepmc3.tree.detectorsim.root",
+    shell:
+        """
+echo "Simulating detector response!"
+source strict-mode.sh
+source benchmarks/u_rho/setup.config $*
+if [ -f ${JUGGLER_IN_FILE} ]; then
+  echo "ERROR: Input simulation file does ${JUGGLER_IN_FILE} not exist."
+else
+  echo "GOOD: Input simulation file ${JUGGLER_IN_FILE} exists!"
+fi
+# Simulate
+ddsim --runType batch \
+      -v WARNING \
+      --numberOfEvents ${JUGGLER_N_EVENTS} \
+      --part.minimalKineticEnergy 100*GeV  \
+      --filter.tracker edep0 \
+      --compactFile ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml \
+      --inputFiles {input} \
+      --outputFile  {output}
+if [[ "$?" -ne "0" ]] ; then
+  echo "ERROR running ddsim"
+  exit 1
+fi
 """
 
 
